---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: packages-src-in
  - name: libyaml-test
  - name: ruby
  - name: bundler-blob
  - name: rubygems-blob
outputs:
  - name: packages-src-out
run:
  path: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/update-packages.sh
params:
  aws_secret_access_key: ""
  aws_access_key_id: ""
