---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: openstack-lifecycle-stemcell
  - name: terraform-lifecycle
outputs:
  - name: output
run:
  path: bosh-cpi-src-in/ci/tasks/run-lifecycle.sh
params:
  BOSH_OPENSTACK_DOMAIN:                   ""
  BOSH_OPENSTACK_AUTH_URL_V2:              ""
  BOSH_OPENSTACK_USERNAME_V2:              ""
  BOSH_OPENSTACK_API_KEY_V2:               ""
  BOSH_OPENSTACK_AUTH_URL_V3:              ""
  BOSH_OPENSTACK_USERNAME_V3:              ""
  BOSH_OPENSTACK_API_KEY_V3:               ""
  BOSH_OPENSTACK_PROJECT:                  ""
  BOSH_OPENSTACK_TENANT:                   ""
  BOSH_CLI_SILENCE_SLOW_LOAD_WARNING:      ""
  BOSH_OPENSTACK_VOLUME_TYPE:              ""
  BOSH_OPENSTACK_CONNECT_TIMEOUT:          ""
  BOSH_OPENSTACK_READ_TIMEOUT:             ""
  BOSH_OPENSTACK_WRITE_TIMEOUT:            ""
  BOSH_OPENSTACK_DEFAULT_KEY_NAME:         ""
  BOSH_OPENSTACK_CA_CERT:                  ""
  BOSH_OPENSTACK_FLAVOR_WITH_NO_ROOT_DISK: ""
  BOSH_OPENSTACK_AVAILABILITY_ZONE:        replace-me

