---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: terraform
  - name: bosh-deployment
outputs:
  - name: director-deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/deploy-old-director.sh
params:
  distro:                                 ""
  director_ca:                            ""
  director_ca_private_key:                ""
  bosh_openstack_ca_cert:                 replace-me
  v3_e2e_private_key_data:                ""
  old_bosh_with_registry_version:         ""
  old_bosh_with_registry_sha1:            ""
  bosh_vcap_password:                     ""
  v3_e2e_flavor:                          ""
  v3_e2e_connection_timeout:              ""
  v3_e2e_read_timeout:                    ""
  v3_e2e_state_timeout:                   ""
  v3_e2e_write_timeout:                   ""
  v3_e2e_bosh_registry_port:              ""
  v3_e2e_api_key:                         ""
  v3_e2e_auth_url:                        ""
  v3_e2e_project:                         ""
  v3_e2e_domain:                          ""
  v3_e2e_username:                        ""
  internal_ntp:                           ""
  old_openstack_cpi_release_version:      ""
  old_openstack_cpi_release_sha1:         ""
  old_bosh_stemcell_name:                 ""
  old_bosh_stemcell_version:              ""
  old_bosh_stemcell_sha1:                 ""
