---
custom:
  tags:
    default: &tags []
    suse-liberty: ['suse-liberty']
    suse-mitaka: ['suse-mitaka']
    suse-newton: ['suse-newton']
    blue-box: ['blue-box']
  timeouts:
    long: &timeouts-long 2h

jobs:
  - name: auto-update
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  get: bosh-cpi-src-in, tags: *tags, timeout: *timeouts-long}
#        - {trigger: true,  get: pipeline-time-trigger, tags: *tags, timeout: *timeouts-long}

      - task: auto-update-gems
        tags: *tags
        timeout: *timeouts-long
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/auto-update-gems.yml

resources:
  - name: bosh-cpi-src-in
    type: git
    tags: *tags
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: auto-update
      ignore_paths:
        - releases/bosh-openstack-cpi/**
        - .final_builds/**
        - docs/**
        - README.md

#  - name: pipeline-time-trigger
#    type: time
#    tags: *tags
#    source:
#      interval: 2h
