---
jobs:
  - name: update-gems
    serial: true
    plan:
      - aggregate:
        - {trigger: false,  get: bosh-cpi-src-in,       tags: ((worker_tags)), timeout: 2h}
        - {trigger: false,  get: gems-src-in,           tags: ((worker_tags)), timeout: 2h}
        - {trigger: true,   get: pipeline-time-trigger, tags: ((worker_tags)), timeout: 2h}

      - task: update-gems
        tags: ((worker_tags))
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/update-gems.yml

      - put: gems-src-out
        tags: ((worker_tags))
        timeout: 2h
        params: {repository: gems-src-out, force: true}

  - name: update-metalinks
    serial: true
    plan:
      - aggregate:
        - {trigger: true,   get: pipeline-time-trigger, tags: ((worker_tags)), timeout: 2h}
        - {trigger: false,  get: bosh-cpi-src-in,       tags: ((worker_tags)), timeout: 2h}
        - {trigger: false,  get: metalink-src-in,       tags: ((worker_tags)), timeout: 2h}

      - task: update-metalinks
        tags: ((worker_tags))
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/update-metalinks.yml

      - put: metalink-src-out
        tags: ((worker_tags))
        timeout: 2h
        params: { repository: metalink-src-out, force: true}

  - name: update-packages
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src-in,  tags: ((worker_tags)), timeout: 2h}
        - {trigger: false, get: packages-src-in,  tags: ((worker_tags)), timeout: 2h}
        - {trigger: false, get: validator-src-in, tags: ((worker_tags)), timeout: 2h}
        - {trigger: true,  get: libyaml-test,     tags: ((worker_tags)), timeout: 2h}
        - {trigger: true,  get: ruby,							tags: ((worker_tags)), timeout: 2h}
        - {trigger: true,  get: bundler-blob,     tags: ((worker_tags)), timeout: 2h}
        - {trigger: true,  get: rubygems-blob,    tags: ((worker_tags)), timeout: 2h}

      - task: update-packages
        tags: ((worker_tags))
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/update-packages.yml
        params:
          aws_access_key_id: ((s3_openstack_cpi_blobs_access_key))
          aws_secret_access_key: ((s3_openstack_cpi_blobs_secret_key))

      - task: verify-cpi
        tags: ((worker_tags))
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/verify-cpi.yml

      - put: packages-src-out
        tags: ((worker_tags))
        timeout: 2h
        params: {repository: packages-src-out, force: true}

  - name: gems-pull-request
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src-in, passed: [update-gems], tags: ((worker_tags)), timeout: 2h}
        - {trigger: true, get: gems-src-out,    passed: [update-gems], tags: ((worker_tags)), timeout: 2h}

      - task: pull-request
        tags: ((worker_tags))
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/gems-pull-request.yml
        params:
          bosh_openstack_cpi_release_github_token: ((bosh-openstack-cpi-release-github-token))
          bosh_openstack_cpi_release_github_key:   ((bosh-openstack-cpi-release-github-key))

  - name: packages-pull-request
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src-in,  passed: [update-packages], tags: ((worker_tags)), timeout: 2h}
        - {trigger: true, get: packages-src-out, passed: [update-packages], tags: ((worker_tags)), timeout: 2h}

      - task: pull-request
        tags: ((worker_tags))
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/packages-pull-request.yml
        params:
          bosh_openstack_cpi_release_github_token: ((bosh-openstack-cpi-release-github-token))
          bosh_openstack_cpi_release_github_key:   ((bosh-openstack-cpi-release-github-key))

resources:
  - name: bosh-cpi-src-in
    type: git
    tags: ((worker_tags))
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: master

  - name: packages-src-in
    type: git
    tags: ((worker_tags))
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: packages-auto-update

  - name: packages-src-out
    type: git
    tags: ((worker_tags))
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch:      packages-auto-update
      private_key: ((bosh-openstack-cpi-release-github-key))

  - name: metalink-src-in
    type: git
    tags: ((worker_tags))
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch:      metalink-update

  - name: metalink-src-out
    type: git
    tags: ((worker_tags))
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch:      metalink-update
      private_key: ((bosh-openstack-cpi-release-github-key))

  - name: gems-src-out
    type: git
    tags: ((worker_tags))
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch:      gems-auto-update
      private_key: ((bosh-openstack-cpi-release-github-key))

  - name: gems-src-in
    type: git
    tags: ((worker_tags))
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: gems-auto-update

  - name: validator-src-in
    type: git
    tags: ((worker_tags))
    source:
      uri: https://github.com/cloudfoundry-incubator/cf-openstack-validator
      branch: master

  - name: pipeline-time-trigger
    type: time
    tags: ((worker_tags))
    source:
      interval: 24h

  - name: rubygems-blob
    type: metalink-repository
    tags: ((worker_tags))
    source:
      uri: https://raw.githubusercontent.com/cloudfoundry-incubator/bosh-openstack-cpi-release/metalink-update/rubygems_metalink
      version: ^2

  - name: bundler-blob
    type: metalink-repository
    tags: ((worker_tags))
    source:
      uri: https://raw.githubusercontent.com/cloudfoundry-incubator/bosh-openstack-cpi-release/metalink-update/bundler_metalink
      version: ^1

  - name: libyaml-test
    type: dynamic-metalink
    tags: ((worker_tags))
    source:
      version: ^0
      version_check: |
       git ls-remote --tags https://github.com/yaml/libyaml.git \
         | cut  -f2 \
         | grep -v '\^{}' \
         | grep -E '^refs/tags/.+$' \
         | sed  -E 's/^refs\/tags\/(.+)$/\1/'  \
         | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
      metalink_get: |
        export name="yaml-${version}.tar.gz"
        export url="http://pyyaml.org/download/libyaml/yaml-${version}.tar.gz"
        export size=$( curl --silent --head "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )
        jq -n '
        {
         "files": [
          {
           "name": env.name,
           "urls": [ { "url": env.url } ],
           "size": env.size | tonumber
          }
         ]
        }'

  - name: ruby
    type: dynamic-metalink
    tags: ((worker_tags))
    source:
      version: "2.4.x"
      version_check: |
        curl --silent --location http://cache.ruby-lang.org/pub/ruby/index.txt \
          | grep "tar.gz" \
          | awk '{print $1}' \
          | grep -E 'ruby-[0-9]+\.[0-9]+\.[0-9]+$' \
          | sed -e "s/^ruby-//"
      metalink_get: |
        export name="ruby-${version}.tar.gz"
        export version_entry="$(curl --silent --location http://cache.ruby-lang.org/pub/ruby/index.txt | grep -E "${version//./\\.}\s" | grep "tar.gz")"
        export url="$(echo "$version_entry" | awk '{print $2}')"
        export sha256="$(echo "$version_entry" | awk '{print $4}')"
        export size="$(curl --silent --head "$url" | grep -i Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]')"
        jq -n '
        {
         "files": [
          {
           "name": env.name,
           "urls": [ { "url": env.url } ],
           "hashes": [{ "type": "sha-256", "hash": env.sha256 }],
           "size": env.size | tonumber
          }
         ]
        }'

resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
