---
jobs:
  - name: auto-update-gems
    serial: true
    plan:
      - aggregate:
        - {trigger: false,  get: bosh-cpi-src-in,       tags: ['blue-box'], timeout: 2h}
        - {trigger: true,   get: pipeline-time-trigger, tags: ['blue-box'], timeout: 2h}

      - task: auto-update-gems
        tags: ['blue-box']
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/auto-update-gems.yml

      - put: bosh-cpi-src-out
        tags: ['blue-box']
        timeout: 2h
        params: {repository: bosh-cpi-src-out/repo, force: true}
  - name: auto-update-packages
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  get: bosh-cpi-src-out, passed: [auto-update-gems], tags: ['blue-box'], timeout: 2h}

      - task: auto-update-packages
        tags: ['blue-box']
        timeout: 2h
        file: bosh-cpi-src-out/ci/pipelines/auto-update/tasks/auto-update-packages.yml

      - put: bosh-cpi-src-out
        tags: ['blue-box']
        timeout: 2h
        params: {repository: bosh-cpi-src-updated-packages-out/repo, force: true}

  - name: pull-request
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src-out, passed: [auto-update-packages], tags: ['blue-box'], timeout: 2h}

      - task: pull-request
        tags: ['blue-box']
        timeout: 2h
        file: bosh-cpi-src-out/ci/pipelines/auto-update/tasks/pull-request.yml
        params:
          bosh_openstack_cpi_release_github_token: {{bosh-openstack-cpi-release-github-token}}
          bosh_openstack_cpi_release_github_key:   {{bosh-openstack-cpi-release-github-key}}

resources:
  - name: bosh-cpi-src-in
    type: git
    tags: ['blue-box']
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: wip-auto-update

  - name: bosh-cpi-src-out
    type: git
    tags: ['blue-box']
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch:      wip-ci-auto-update
      private_key: {{bosh-openstack-cpi-release-github-key}}

  - name: pipeline-time-trigger
    type: time
    tags: ['blue-box']
    source:
      interval: 24h
